version: '3'
services:
  nginx:
    container_name: nginx
    image: dmp1ce/nginx-debug
    restart: always
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./default.conf:/etc/nginx/conf.d/default.conf"
      - "./server-cert:/etc/server-cert"
      - "./client-cert:/etc/client-cert"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - RUNNING_IN_DOCKER=true
    networks:
      cosd_net:
        ipv4_address: 172.30.1.15
networks:
  cosd_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
